### PR TITLE
Updates Python soup_adapter to use BeautifulSoup 4

### PR DESCRIPTION
**Pull request by romanvm**
Also fixes the indentation according to PEP-8

### CODE REVIEW

**Comment by romanvm** [comment]
I signed it!

**Comment by rofl0r** [comment]
nice work! however i personally would prefer if you had done the gratuitous whitespace changes in a separate commit, since it makes it hard to see what you changed.

**Comment by romanvm** [comment]
Sorry but all my code editors tools are set for 4 spaces in Python. The changes are not that big: lines 29, 60, 108-112, and 117 in the changed file. Default parser `html.parser` is set just to suppress BS4 warnings, because it does not really parse anything.

**Comment by DemiMarie** [comment]
Ping?

**Comment by samreflexive** [comment]
Bump!

**Comment by wumpus** [comment]
beautifulsoup4 was released in 2014, this PR is from 2017, the last accepted PR in this project is 2016, and it's now 2018.

**Comment by romanvm** [comment]
If you really need BS4 support, I'd recommend Sigil fork: https://github.com/Sigil-Ebook/sigil-gumbo

However, according to my benchmarks, gumbo + BS4 does not offer any speed benefits over BS4 + html5lib, probably because of ctypes bindings overhead. I even tried to write native Python bindings with Pybind11 library but speed gain was not that significant. Anyway, the library seems abandoned, and html5lib is a safe bet if you need a compliant html5 Python parser.

**Comment by romanvm** [comment]
Too old to be still relevant.

**Pull request closed without merging**
