### PR TITLE
Altversion2 - an attempt to put vmg's approach on today's master

### PR DESCRIPTION
**Pull request by kevinhendricks**
Hi,

I tried to implement vmg's approach over currrent master without any of my changes.  I also built things incrementally so you can pick and choose which commits you want for your tree if any.

This should allow people to check out the speedups, size, etc using current master as the basis.

I did not add any additional tags or reorder any to maintain your api per your wishes

All credit goes to vmg here.

### CODE REVIEW

**Comment by nostrademons** [comment]
Benchmark results (both run with -O2 on my Ubuntu laptop):

Current master:
hacker_news.html: 6149 microseconds.
html5_spec.html: 894692 microseconds.
xinhua.html: 31831 microseconds.
baidu.html: 7118 microseconds.
yahoo.html: 33704 microseconds.
google.html: 38350 microseconds.
bbc.html: 11585 microseconds.
arabic_newspapers.html: 9512 microseconds.
wikipedia.html: 51014 microseconds.

This branch:
hacker_news.html: 6670 microseconds.
html5_spec.html: 817888 microseconds.
xinhua.html: 24327 microseconds.
baidu.html: 5362 microseconds.
yahoo.html: 25621 microseconds.
google.html: 23149 microseconds.
bbc.html: 8404 microseconds.
arabic_newspapers.html: 7425 microseconds.
wikipedia.html: 44868 microseconds.

Speedup seems to be on the order of 20-30%, similar to what @vmg reported.  Good enough for me.  Thanks for putting this together!  I'd appreciate if you could address the couple comments on individual commits here, but if not, I can merge this within a day or so and then fix them later myself.

As for creating a development branch for breaking changes - I think this is a good idea.  It's getting annoying having to update all the outstanding pull requests every time a large change goes in.  I'd like to release 0.9.3 first (including these changes, html5lib test fixes, the fix for the assertion errors Geoffrey reported, and assorted other bugfixes) before creating yet another branch that will need to be updated, though.

**Comment by vmg** [comment]
@kevinhendricks: Thanks for taking the time to backport this. I really appreciate. I think updating the `template` branch to merge on top of this would be a nice next step. Do you have time to work on that, or shall I give it a go?

**Comment by kevinhendricks** [comment]
@nostrademons

I would guess the bottleneck is now in looking up the GumboTag enum value for a given tag string.  My own repo version still sorts the gumbo tags in alphabetical order and uses binary search to look up the tags.  In doing this it improves run time by offloading it by presorting which means for a static set of strings to search, binary search should even be faster than dynamic red black types of approaches.

The only specific comment I have received so far is the comment that you do not want well_formed.cc which I can easily remove and of course update Makefile.am too.

Where can I find the comments on the other things you would like to see changed?

**Comment by nostrademons** [comment]
That's the main one.  There's also a nitpick in has_an_element_in_scope_with_tagname where there's a "bool found = ...; return found" that could be condensed into a direct return.

These show up as individual comments (referencing specific locations in the source code) in the thread for this pull request for me...do they not for you?

**Comment by nostrademons** [comment]
You've got them.  I'll wait for the Travis run to complete and then merge if there're no major problems.

**Comment by kevinhendricks** [comment]
@vmg

Always happy to help.  I have a class to teach tomorrow but I should be able to squeeze in some time over this weekend (and next week is reading week at our university) and take a shot at it.  So as long as you can wait until Saturday, I am happy to take a first shot at it.

Kevin

**Comment by vmg** [comment]
@kevinhendricks You sound busy, so I'm gonna go ahead and work on the template branch.

> I would guess the bottleneck is now in looking up the GumboTag enum value for a given tag string.

I have a patch for this too: it uses a perfect hash set (gperf) improving lookup performance 100x compared to the current implementation. It is pretty nice. I'll upstream this.

I'm also going to upstream the `gumbo_malloc` changes that you can see on my `parser.c` and that you commented positively on the other PR. Hopefully @nostrademons will find them appropriate too.

**Comment by vmg** [comment]
Btw, thanks again for this PR. Can't wait for it to to get merged. I'll rebase `template` on top and pile up the other patches. You go focus on teaching and making the word a better place :))

**Comment by kevinhendricks** [comment]
@vmg,

A perfect hash set.  Is it built during pre-processing  or dynamically once during runtime start-up of the parser?  Can you define "perfect"?  To me that would mean no collisions are possible (no need for a next entry link to allow for two or more strings to have the same hash value).  Is that what you are saying?  Do you then back out the proper hash function to prevent collisions from the set of strings first?  The reason I ask is that I have greatly extended the set of recognized tags to be over 255 (adding in some epub:switch, epub:case:, epub:default, epub:trigger, full svg, and all mathml presentation elements).  Would I be able to use your perfect hash function or need to find one of my own?

**Comment by kevinhendricks** [comment]
@vmg

In other words... "old man you are slowing me down!"  ;-)

Take care,

Kevin

**Comment by nostrademons** [comment]
The gumbo_malloc changes remove the ability to use an outside allocator, right?  The reason for the configurable allocator is because in Gumbo's initial use-case, we were thinking we'd use an arena for parsing, since it was part of a large precompilation step where all the intermediate data structures could be thrown away at once.  It's also since been useful for debugging & performance tweaking, since it gives the ability to swap out the allocator for one that keeps statistics of allocation sizes & frequencies.

I'm open to removing the configurable allocator; I'm not certain anyone's actually using it, and there is a cost in conditional branches to keeping it configurable.  It'd have to wait until 1.0 though, as it's a breaking change, and we should solicit feedback from other users before merging upstream.

I like the idea of a perfect hash function for tag lookups.  (@kevinhendricks: he's using [gperf](https://www.gnu.org/software/gperf/manual/gperf.html), the Gnu Perfect Hashtable generator.)  I'd thought of using Ragel to generate a FSM for matching, but I suspect a hashtable is faster.  Will the generated code be checked in?  One of the key requirements for Gumbo is to eliminate outside dependencies.  It's okay if someone needs to download Ragel if they want to work on char_refs or gperf if they want to work on tag sets, but I want ordinary users of the library to be able to drop it in and not hunt down a bunch of dependencies.

**Comment by kevinhendricks** [comment]
@nostrademons

In case it helps, the Travis CI builds on Mac are always failing in trying to build gumbo_test as follows:

/Applications/Xcode.app/Contents/Developer/usr/bin/make  gumbo_test
  CXX      tests/gumbo_test-attribute.o
In file included from tests/attribute.cc:22:
In file included from ./gtest/include/gtest/gtest.h:57:
In file included from ./gtest/include/gtest/internal/gtest-internal.h:40:
./gtest/include/gtest/internal/gtest-port.h:499:13: fatal error: 'tr1/tuple' file not found
#   include <tr1/tuple>  // NOLINT
            ^
1 error generated.
make[1]: *** [tests/gumbo_test-attribute.o] Error 1
make: *** [check-am] Error 2

So it looks like gtest/internal/gtest.port.h is looking for a header that does not seem to exist on Mac OSX (at least that version of it).

I am using gtest-1.7.0 and Mac OSX 10.10.1 and do not get this failure at all.

**Comment by kevinhendricks** [comment]
@nostrademons

> I like the idea of a perfect hash function for tag lookups. (@kevinhendricks: he's using gperf, the Gnu Perfect Hashtable generator.) 

Okay, grabbed version 3.0.4 from gnu.org and built it and passed in my 256 long tag list and associated enum values and it generated a nice hash function that only really used the first 3 chars and the last char of each word, but then ended up with a hashtable size of over 950 elements in size.  That is blowing things up by almost a factor of 4.

I would assume a smaller hashtable would be more conducive for fitting in cache lines.  I suppose there must be some options to control all of this so I will read up on it.  Having a smaller table with a few nodes needing to walk a list due to collisions with a general hash function might be faster as it would be more localized.  We will also still have the issue of dealing with all of the mixed case SVG tag names. but the generated hash code strcmp could be swapped with its case insensitive cousin.  Hopefully it will do better with the official set of around 150 tags now recognized.

Thanks for the link.

**Comment by vmg** [comment]
I'm afraid I got distracted with Valentine's day business and haven't found time to work on the template rebase. I'll get to it on Monday if @kevinhendricks still hasn't.

Also don't worry about `gpef`, I've got some tricks under my sleeve -- just wait and see my pull request. :)

**Comment by kevinhendricks** [comment]
@vmg,

I started on the template stuff.  If I can get it working correctly before monday I will post it.

**Comment by kevinhendricks** [comment]
@vmg

I think my altversion2 branch at https://github.com/kevinhendricks/gumboparser now has the needed template support changes in place but all I have been able to test with is the one template related set of tests in tests/parser.cc called TestTemplateInForeignContent.

It really needs to be tested much more that that given how invasive that set of changes were.    I will modify my serialize routines to make sure they recreate the template nodes properly so at least I can see if the basic use of templates seems to be working.

Grab it to continue building upon if you want.

**Comment by kevinhendricks** [comment]
@vmg,

I checked out the html5lib_tests and unpacked them and copied them into testdata and ran the html5lib_adapter_test.py.

With official master I get:

----------------------------------------------------------------------
Ran 1532 tests in 0.599s

FAILED (failures=164)



In altversion2 and the template pieces I get:

----------------------------------------------------------------------
Ran 1532 tests in 0.568s

FAILED (failures=76)


So we now pass 88 more tests with the template stuff in place.  I really have no idea how many of those 1532 tests are template related so it would be hard to say if I converted the template changes 100% perfectly but it does look good.

**Comment by kevinhendricks** [comment]
@vmg,

I am working my way through the template related parts of the spec and have found and fixed a few bugs so far that were actually in the original patch.

I am now down to 38 errors out of 1532 tests.  I will keep tracking down any template related ones and keep add ing fixes to this branch.

**Comment by kevinhendricks** [comment]
@vmg

I have found a number of bugs in template handling and fixed most of those, added in the rtc tag and fixed the ruby related bugs, made a few "corrections" to make things look more like the spec in a places, and now I am down to just 27 failures out of 1532 tests run by "html5lib_adapter_test.py" to test the parser.

What I have found is that I do not agree with many of the remaining errors at all.  For example about 5 of them have to do with literally removing "perfectly" legal SVG attributes (not just adjusting their case).  This is silly and I can find no where in the html5.1 nightly spec or anyplace that tells you to remove valid svg attributes (or even invalid ones).  Under adjust SVG attributes it says that if and only if an attribute is in the table, adjust ints name.  There is nothing about removing it.


For example:
```
<!DOCTYPE html><body><svg attributeName='' attributeType='' baseFrequency='' baseProfile='' calcMode='' clipPathUnits='' contentScriptType='' contentStyleType='' diffuseConstant='' edgeMode='' externalResourcesRequired='' filterRes='' filterUnits='' glyphRef='' gradientTransform='' gradientUnits='' kernelMatrix='' kernelUnitLength='' keyPoints='' keySplines='' keyTimes='' lengthAdjust='' limitingConeAngle='' markerHeight='' markerUnits='' markerWidth='' maskContentUnits='' maskUnits='' numOctaves='' pathLength='' patternContentUnits='' patternTransform='' patternUnits='' pointsAtX='' pointsAtY='' pointsAtZ='' preserveAlpha='' preserveAspectRatio='' primitiveUnits='' refX='' refY='' repeatCount='' repeatDur='' requiredExtensions='' requiredFeatures='' specularConstant='' specularExponent='' spreadMethod='' startOffset='' stdDeviation='' stitchTiles='' surfaceScale='' systemLanguage='' tableValues='' targetX='' targetY='' textLength='' viewBox='' viewTarget='' xChannelSelector='' yChannelSelector='' zoomAndPan=''></svg>

Expected:
<!DOCTYPE html>
<html html>
  <html head>
  <html body>
    <svg svg>
      attributeName=""
      attributeType=""
      baseFrequency=""
      baseProfile=""
      calcMode=""
      clipPathUnits=""
      diffuseConstant=""
      edgeMode=""
      externalresourcesrequired=""
      filterUnits=""
      filterres=""
      glyphRef=""
      gradientTransform=""
      gradientUnits=""
      kernelMatrix=""
      kernelUnitLength=""
      keyPoints=""
      keySplines=""
      keyTimes=""
      lengthAdjust=""
      limitingConeAngle=""
      markerHeight=""
      markerUnits=""
      markerWidth=""
      maskContentUnits=""
      maskUnits=""
      numOctaves=""
      pathLength=""
      patternContentUnits=""
      patternTransform=""
      patternUnits=""
      pointsAtX=""
      pointsAtY=""
      pointsAtZ=""
      preserveAlpha=""
      preserveAspectRatio=""
      primitiveUnits=""
      refX=""
      refY=""
      repeatCount=""
      repeatDur=""
      requiredExtensions=""
      requiredFeatures=""
      specularConstant=""
      specularExponent=""
      spreadMethod=""
      startOffset=""
      stdDeviation=""
      stitchTiles=""
      surfaceScale=""
      systemLanguage=""
      tableValues=""
      targetX=""
      targetY=""
      textLength=""
      viewBox=""
      viewTarget=""
      xChannelSelector=""
      yChannelSelector=""
      zoomAndPan=""

Notice the expected set of svg attributes has had both the  contentScriptType='' and contentStyleType='' attributes removed form the input.
This is not spec and this is not a sanitizer (they are legal svg attributes) and I would not want a parser that hacked away specific attributes.

This same error or related occurs in about 5 or so of the tests.

And there are a number of template related failures in the testsuite that make no sense to me either:

For example:

Input:
<body><template><template><tr></tr></template><td></td></template>

Expected:
<html html>
  <html head>
  <html body>
    <html template>
      <html template>
        <html tr>
        <html td>

Received:
<html html>
  <html head>
  <html body>
    <html template>
      <html template>
        <html tr>
      <html td>


Here we have a nested template (which is legal) and the proper explicit close tags are there so why do they have the final td element to be a child of the second template, when that second template was clearly properly closed and should have been popped of the stack before it.

The altversion2 code right now seems to be exactly correct but not equal to the expected.  There are a few failing cases related to this that I would like to clear up but from my reading of the spec and walking the official spec like code, our version is correct not theirs.

Can you explain why I am wrong about either of these failures?  If not, we should really get these tests removed or fixed as they are driving me crazy.

I am happy to track down and fix template test failures to make them work like the spec, but having bad tests is something that really needs to be fixed.  I think for the missing attributes cases, someone just manually edited the expected test results but forgot to check the inputs.

**Comment by vmg** [comment]
This is an amazing job, @kevinhendricks. Can't wait to get to work tomorrow and start adding stuff on top of your branch. FWIW, I have no opinion nor insight regarding the remaining errors, but our resident guru @aroben surely does. I'm sure we'll get this test suite at 100% as soon as he shows up here (and I'll just week working on making the implementation fast ;).

**Comment by kevinhendricks** [comment]
@vmg

I am still missing the get_appropriate_insert_location implementation from the template code into the right places in the altversion branch.  So hopefully I will have it in by late tonight and get a few more of those errors gone.  The master version has inlined it and ignored the template stuff and the new version needs to be used instead.

**Comment by kevinhendricks** [comment]
@vmg

Okay, I have fixed a bunch on non-spec handling of EOF tokens and now we are down to just 12 failures with the altversion2 tree using html5lib_adapter_test.py

And none of them seem to be valid in my opinion ;-))

The remaining issue seems to come from these areas:

  - nested template tags. As far as I can tell we are spec and they are not (this is based off of html 5.1 nightly version of the spec).  I think the tests are wrong here. I would like to be shown why these expected test results are correct.

  - a second group of tests that actually remove SVG attributes which the spec never calls for (these are incorrect tests in my opinion also) and I think someone just forgot to remove those no longer tested for SVG attributes from the input to those tests.  These must be bogus.

  - 1 test using style in head  with unsafe use of "<" and ">"  (not sure about this one at all as the parser was not confused by it at all)

  - 1 test that complains about not stripping out the meta charset information (which is something I feel that preprocessors that convert to utf-8 should do and not the job of the parser)

  - 1 test about 4 nested bold tags in a row, that I think violates the Noah's ark rule of 3 in the set of active formatting tags.

Overall, I am very happy with it but would like to get the nested template issues nailed down if they are even in fact true issues!

I am planning to create a PR for @nostrademons to see if he will accept this tree as the new trunk for a "development" branch (not stable branch) he said he might consider.  It can't go in the current master as it adds new tags like "rtc".

If you can add in
	- your speedups
	- document fragment pieces
	- your gumbo_malloc and gumbo_free and removing all of the unnecessary passing of "parser" just to handle memory allocation everywhere

Then we should end up with something pretty complete for moving forward.  We can add in the prev/next stuff (although that seems to be needed only for beautiful soup 3 - when using bs4 and html5lib parser you don't get them set), and the CDATA stuff after we get these other pieces in place.


Have fun!
Kevin

**Comment by kevinhendricks** [comment]
@vmg 
All commits you want are to the altversion2 branch at github.com/kevinhendricks/gumbo-parser.  None of those changes are yet in the master at my site.

**Pull request merged**
