### PR TITLE
Fix empty the end of the tag <form>

### PR DESCRIPTION
**Pull request by lifenjoiner**
Fix for issue #350. Shall we?

### CODE REVIEW

**Comment by lifenjoiner** [comment]
I signed it!

**Comment by lifenjoiner** [comment]
Travis CI build failed on it's own configuration.

**Comment by craigbarnes** [comment]
This patch causes a tree construction test to fail. The patch in PR #372 works though.

**Comment by lifenjoiner** [comment]
Thanks for your reply! @craigbarnes 
You are right. It works on daily well formed HTML files, but not the quirk formed. I didn't pull the submodules recursively ...

**Pull request closed without merging**
