### PR TITLE
Handle CDATA properly

### LINKED ISSUE #266: GUMBO_NODE_CDATA unused?
It seems to me that, as the code stands, a `GumboNode` with a type of `GUMBO_NODE_CDATA` can never actually appear in the parse tree. Is that correct? If so, would it be worth adding a comment in `gumbo.h`, so that people know it's safe to omit handling it when walking the tree?

### PR DESCRIPTION
**Pull request by nostrademons**
This changes the tokenizer so that CDATA sections are properly plumbed through to the parser, so that the parser actually produces GUMBO_NODE_CDATA nodes.  Fixes #266.  @craigbarnes, would you like to review?

### CODE REVIEW

**Comment by nostrademons** [comment]
I've updated this pull request to fix the failing test case and compiler warning.  I'll let it sit for a bit, but plan to merge fairly soon because I'd like to get it in to master before merging @vmg and @kevinhendricks changes in to a v0.10 branch.  Hopefully somebody can get around to reviewing it shortly.

**Comment by vmg** [comment]
Looks good to me!

**Comment by aroben** [comment]
As far as I can tell from the spec [[1](https://html.spec.whatwg.org/multipage/syntax.html#cdata-section-state)], tokenizing a CDATA section just emits the text contained within the section and never produces a "CDATA node". So it doesn't seem like `GUMBO_NODE_CDATA` should exist at all. Am I missing something?

**Comment by kevinhendricks** [comment]
@aroben
I think the idea was to allow a serializer to reproduce the tree as closely as possible to the original.  Without a CDATA node type, this information would be lost to the tree-walkers/serializers.

**Comment by aroben** [comment]
I see, so `GUMBO_NODE_CDATA` is like `GUMBO_NODE_WHITESPACE`: it's really just a text node, but with a tiny bit of extra information.

**Comment by kevinhendricks** [comment]
@aroben - yes and nicely only if you care to use that extra information.  So it can not hurt so to speak.

**Comment by nostrademons** [comment]
Discussion was in bug #266. GUMBO_NODE_CDATA already existed in gumbo.h, but was never actually being set. Given gumbo's primary audience of tool writers and the existence of GUMBO_NODE_WHITESPACE already, we felt the extra node type would give the most useful information to client code.

**Pull request merged**
